# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 104bb53964ba92290110abf4b2f8e2c99812fef45a947c04d9bd5276a27e14ef7b76b83412b14462e573fc06cda32b1ffd36a6ea56dd6b07e50a779e7a73a904

test:
  secret_key_base: 07fffee4aea8133f4870b277caf97637aa19dc4b9a236351b379cea8d75e03a0663b0c81af2a1b6c31c1299c1e54a3a72a256fb1e0e9e21fb38cb954796af235

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
